# Generated by Django 5.0.8 on 2024-08-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_nutrient_remove_ingredient_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='text',
            field=models.TextField(),
        ),
    ]
