# Generated by Django 5.0.8 on 2024-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_alter_ingredient_quantity_alter_ingredient_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
