# Generated by Django 5.0.8 on 2024-08-13 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_alter_ingredient_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='uri',
            field=models.CharField(default='default_uri', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mycookbook',
            unique_together={('user', 'recipe')},
        ),
    ]
