# Generated by Django 5.0.8 on 2024-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_recipe_uri_alter_mycookbook_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='uri',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
