# Generated by Django 5.0.8 on 2024-08-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_alter_recipe_uri'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'text', 'quantity', 'measure', 'food', 'weight')},
        ),
        migrations.AlterUniqueTogether(
            name='nutrient',
            unique_together={('label', 'quantity', 'unit')},
        ),
    ]
