# Generated by Django 5.0.8 on 2024-08-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_alter_ingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet_labels',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='health_labels',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
