# Generated by Django 5.0.8 on 2024-08-11 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet_app', '0001_initial'),
        ('recipe_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydietplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailydietplanmeal',
            name='daily_diet_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.dailydietplan'),
        ),
        migrations.AddField(
            model_name='dailydietplanmeal',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe'),
        ),
        migrations.AddField(
            model_name='dailydietplan',
            name='meals',
            field=models.ManyToManyField(through='diet_app.DailyDietPlanMeal', to='recipe_app.recipe'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietplanrecipe',
            name='diet_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.dietplan'),
        ),
        migrations.AddField(
            model_name='dietplanrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='recipes',
            field=models.ManyToManyField(through='diet_app.DietPlanRecipe', to='recipe_app.recipe'),
        ),
    ]
