# Generated by Django 5.0.8 on 2024-08-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entry_text', models.TextField()),
                ('mood', models.IntegerField()),
                ('gratitude_1', models.CharField(max_length=255)),
                ('gratitude_2', models.CharField(max_length=255)),
                ('gratitude_3', models.CharField(max_length=255)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('goals_for_tomorrow', models.TextField(blank=True, null=True)),
                ('goals_reflection', models.TextField(blank=True, null=True)),
                ('mindfulness_practice', models.TextField(blank=True, null=True)),
                ('self_care_activities', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
