# Generated by Django 5.0.8 on 2024-08-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='full_name',
        ),
    ]
