# Generated by Django 5.0.8 on 2024-08-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('diet_app', '0002_initial'),
        ('journal_app', '0002_initial'),
        ('mindfulness_app', '0001_initial'),
        ('recipe_app', '0002_initial'),
        ('user_app', '0004_app_user_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App_User',
            new_name='User',
        ),
    ]
